version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "19"
  jobs:
    post_create_environment:
      - pip uninstall sphinx-rtd-theme

sphinx:
  configuration: docs/source/conf.py

formats: [epub, pdf]

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
