version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    nodejs: "16"

sphinx:
  configuration: docs/source/conf.py

formats: [epub, pdf]

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
